name: Android Build & Unit Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UP JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

#      - name: Get API key
#        run: echo NEWS_API_KEY = "\"$API_KEY\"" > ./local.properties
#        env:
#          API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Build Project
        run: ./gradlew assembleDebug
      - name: Run Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Generate Jacoco Test Reports
        run: |
            ./gradlew jacocoTestReport
            tar -cvf unit-test.zip app/build/jacocoHtml/

#      - name: Upload Unit Test Report
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit-test-reports
#          path: unit-test.zip

      - name: Post Code Coverage Summary
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: detekt
        run: ./gradlew detekt --stacktrace

#      - name: Delete API key file
#        run: rm ./local.properties
